<script type="text/javascript">
//<!--
$(document).ready(function() {
	$.datepicker.regional['zh-CN'] = {
			closeText: '关闭',
			prevText: '&#x3c;上月',
			nextText: '下月&#x3e;',
			currentText: '今天',
			monthNames: ['一月','二月','三月','四月','五月','六月',
			'七月','八月','九月','十月','十一月','十二月'],
			monthNamesShort: ['一','二','三','四','五','六',
			'七','八','九','十','十一','十二'],
			dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],
			dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],
			dayNamesMin: ['日','一','二','三','四','五','六'],
			weekHeader: '周',
			dateFormat: 'yy-mm-dd',
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: true,
			yearSuffix: '年'};
	$.datepicker.setDefaults($.datepicker.regional['zh-CN']);
	
    $("#start_date").datepicker();
    $(" #start_date ").datepicker('setDate', -30);
    $("＃start_date ").datepicker({ hideIfNoPrevNext: true });
    
    $("#end_date").datepicker();
    $(" #end_date").datepicker('setDate', new Date());
});
//-->
</script>
<div class="bc_mod">
			<div class="lan_tit">日志浏览</div>
		</div>
<?php
$this->form->setAttrib('class', 'heng');
$this->form->setAction($this->url());
echo $this->form;
?>
<div class="big-form">
<table>
<tr class="big-form-tit">
    <th>用户名</th>
    <th>事件</th>
    <th>事件类型</th>
    <th>发生时间</th>
</tr>
<?php if (isset($this->paginator)):?>
<?php foreach($this->paginator as $slog) : ?>
<tr>
    <td><?php echo $slog->username;?></td>
    <td nowrap class="fixtd" title=<?php echo $slog->event ?>><?php echo $slog->event;?></td>
    <td><?php echo $slog->eventtype;?></td>
    <td><?php echo $slog->createdate;?></td>
  
<?php endforeach; ?>
<?php endif; ?>
</table>
</div>

<?php echo $this->paginationControl($this->paginator, 'Elastic', 'syslog/pagelist.phtml',
		array(	'usernamelog' => $this->usernamelog,
				'start_date' => $this->start_date,
				'end_date'=> $this->end_date
			)); ?>
<p align="center"><a href="<?php echo $this->url(array('controller'=>'syslog',
        'action'=>'clear'));?>">清空</a></p>