
<script type="text/javascript">
//<!--
$(document).ready(function() {
	$.datepicker.setDefaults($.datepicker.regional['zh-CN']);
	
    $("#start_date").datepicker();
    $(" #start_date ").datepicker('setDate', -30);
    $("＃start_date ").datepicker({ hideIfNoPrevNext: true });
    
    $("#end_date").datepicker();
    $(" #end_date").datepicker('setDate', new Date());
    $("#syslogTable").dataTable( 
  	      { 
  	          iDisplayLength: 10,
  	          bLengthChange: false,
  	          bPaginate: true,
  	          bFilter: false,
  	          oLanguage: {
  	              sProcessing: "正在加载中......",
  	              sLengthMenu: "每页显示 _MENU_ 条记录",
  	              sZeroRecords: "对不起，查询不到相关数据！",
  	              sEmptyTable: "表中无数据存在！",
  	              sInfo: "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
  	              sInfoFiltered: "数据表中共为 _MAX_ 条记录",
  	              sSearch: "搜索",
  	              oPaginate: {
  	                  sFirst: "首页",
  	                  sPrevious: "上一页",
  	                  sNext: "下一页",
  	                  sLast: "末页"
  	              }
  	      }
  	     }
  	    );
    
});
//-->
</script>
<div class="bc_mod">
			<div class="lan_tit">日志浏览</div>
		</div>
<?php
$this->form->setAttrib('class', 'heng');
$this->form->setAction($this->url());
echo $this->form;
?>
<div class="big-form">
<table style="table-layout:fixed" class="display"  id='syslogTable'>
<tr class="big-form-tit">
    <th>用户名</th>
    <th>事件</th>
    <th>事件类型</th>
    <th>发生时间</th>
</tr>
<?php foreach($this->entries as $item) : ?>
<tr>
    <td><?php echo $item->username;?></td>
    <td nowrap class="fixtd" title=<?php echo $item->event ?>><?php echo $item->event;?></td>
    <td><?php echo $item->eventtype;?></td>
    <td><?php echo $item->createdate;?></td>
 </tr> 
<?php endforeach; ?>
</table>
</div>

<p align="center"><a href="<?php echo $this->url(array('controller'=>'syslog',
        'action'=>'clear'));?>">清空</a></p>
