<?php if ($this->pageCount): ?>
<div align="center" class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
   <a href="/syslog?page=<?php echo $this->previous; ?>">&lt; 上一页</a> |
<?php else: ?>
   <span class="disabled">&lt; 上一页</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
     <a href="/syslog?page=<?php echo $page; ?>"><?= $page; ?></a> |
  <?php else: ?>
    <?= $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
   <a href="/syslog?page=<?php echo $this->next; ?>">下一页 &gt;</a>
<?php else: ?>
   <span class="disabled">下一页 &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>