<div class="bc_mod">
			<div class="lan_tit">单位信息浏览</div>
		</div>
<?php
$this->form->setAction($this->url());
echo $this->form;?>
<table>
	<thead>
		<tr>
			<th>用户信息:</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>修改</th>
			<th>删除</th>
			<th>单位名称</th>
		</tr>
		<?php foreach ($this->units as $item) :?>
			    <tr>
			    <th><a href="<?php echo $this->url(
			    array(
			    'controller' => 'unit',
			    'action'     => 'unitupd',
			    'unitid'=>$item->unitid
			    ),
			    'default',true) ?>">修改</a></th>
			    
  				<th><a href="<?php echo $this->url(
			    array(
			    'controller' => 'unit',
			    'action'     => 'unitdel',
			    'unitid'=>$item->unitid
			    ),
			    'default',true) ?>">删除</a></th>

			    <th><?php echo $this->escape($item->unitname) ?></th>
			    </tr>
     			
		 <?php endforeach ?>
		
	</tbody>
</table>
