<div class="bc_mod">
			<div class="lan_tit">系统浏览</div>
		</div>
<?php
$this->title = "系统管理";
$this->headTitle($this->title);
?>
<div class="big-form">
<table>
<tr class="big-form-tit">
<th>删除</th>
<th>修改</th>
<th>系统名称</th>
<th>系统描述</th>
<th>系统状态</th>
<th>系统编号</th>
</tr>
<?php foreach($this->apps as $item) :?>
<tr>
<?php if ($item->enable == 1): ?>
<td class="disabled">删除</td>
<?php else: ?>
<td> <a href="<?php echo $this->url(array('controller'=>'acapplication',
'action'=>'appdelete', 'applicationid'=>$item->applicationid));?>">删除</a>
</td>
<?php endif; ?>
<td>
<a href="<?php echo $this->url(array('controller'=>'acapplication',
'action'=>'appupdate', 'applicationid'=>$item->applicationid));?>">修改</a>
</td>
<td><?php echo $this->escape($item->applicationname);?></td>
<td><?php echo $this->escape($item->description);?></td>
<td><?php echo $this->escape($item->enable);?></td>
<td><?php echo $this->escape($item->apporder);?></td>
</tr>
<?php endforeach; ?>
</table>
</div>




