<script type="text/javascript">
$(function () { 
    $("#applicationTable").dataTable( 
      { 
          iDisplayLength: 10,
          bLengthChange: false,
          bPaginate: true,
          bFilter: false,
          oLanguage: {
              sProcessing: "正在加载中......",
              sLengthMenu: "每页显示 _MENU_ 条记录",
              sZeroRecords: "对不起，查询不到相关数据！",
              sEmptyTable: "表中无数据存在！",
              sInfo: "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
              sInfoFiltered: "数据表中共为 _MAX_ 条记录",
              sSearch: "搜索",
              oPaginate: {
                  sFirst: "首页",
                  sPrevious: "上一页",
                  sNext: "下一页",
                  sLast: "末页"
              }
    
      }
     }
    )
});
</script>
<div class="bc_mod">
			<div class="lan_tit">系统浏览</div>
		</div>
<?php
$this->title = "系统管理";
$this->headTitle($this->title);
$index = 0;
?>
<div class="big-form">
<table style="table-layout:fixed" class="display"  id='applicationTable'>
<thead>
<tr class="big-form-tit">
<th style="width:100px">系统名称</th>
<th style="width:200px">系统描述</th>
<th style="width:70px">系统状态</th>
<th style="width:70px">修改</th>
<th style="width:70px">删除</th>
<th style="width:70px">顺序管理</th>
</tr>
</thead>
<tbody>
<?php foreach($this->apps as $item) :?>
<tr>
<td nowrap class="fixtd" title=<?php echo $item->applicationname ?>><?php echo $this->escape($item->applicationname);?></td>
<td nowrap class="fixtd" title=<?php echo $item->description ?>><?php echo $this->escape($item->description);?></td>
<?php if ($item->enable == 1): ?>
<td>可用</td>
<?php else: ?>
<td>禁用
</td>
<?php endif; ?>
<td>
<a class="btn_edit" href="<?php echo $this->url(array('controller'=>'acapplication',
'action'=>'appupdate', 'applicationid'=>$item->applicationid));?>"></a>
</td>
<?php if ($item->enable == 1): ?>
<td class="disabled">
</td>
<?php else: ?>
<td> <a  class="btn_del" href="<?php echo $this->url(array('controller'=>'acapplication',
'action'=>'appdelete', 'applicationid'=>$item->applicationid));?>"></a>
</td>
<?php endif; ?>
<td>
<a href="<?php echo $this->url(array('controller'=>'acapplication','action'=>'appup', 'appid'=>$item->applicationid, 'prev'=>$this->prevs[$index])) ?>">上移</a>
<a href="<?php echo $this->url(array('controller'=>'acapplication','action'=>'appdown', 'appid'=>$item->applicationid, 'next'=>$this->nexts[$index])) ?>">下移</a>
</td>

</tr>
<?php
$index++;
endforeach; 
?>
</tbody>
</table>
</div>




