<?php echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>网站管理系统</title>
  <?php
		
		echo $this->headLink ()->appendStylesheet ( $this->baseUrl('/css/style.css') )->appendStylesheet ( $this->baseUrl('/css/redmond/jquery-ui-1.8.18.custom.css') );
		
		?>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.7.1.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-ui-1.8.18.custom.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.ui.datepicker-zh-CN.js')?>"></script>
</head>
<body>
	<div id="container">
		<div class="info_top"></div>

		<div id="nav">
		   <div id="menu1">
				<ul id="nav_root_ul">
				    <li class="menu_5"><a href="<?php echo $this->url ( array ('controller' => 'index' ), 'default', true )?>">管理说明</a></li>
					<li class="menu_1"><a href="#">人员信息</a>
						<ul class="nav_mini_ul">
							<li class="m_txt"><a href="<?php echo $this->url(array('controller' => 'user', 'action'=> 'login'),'default', true) ?>"><span>用戶登录</span></a></li>
							<li class="m_txt"><a href="<?php echo $this->url(array('controller' => 'user', 'action'=> 'add'),'default', true) ?>"><span>添加用戶</span></a></li>
							<li class="m_txt"><a href="<?php echo $this->url(array('controller' => 'user', 'action'=> 'search'),'default', true) ?>"><span>浏览用戶</span></a></li>
						</ul></li>
					<li class="menu_2"><a href="#">系統管理</a>
						<ul class="nav_mini_ul">
							<li class="m_txt"><a href="<?php echo $this->url(array('controller'=>'acapplication','action'=>'appadd'),'default', true);?>"><span>添加系統</span></a></li>
							<li class="m_txt"><a href="<?php echo $this->url(array('controller'=>'acapplication','action'=>'index'),'default', true);?>"><span>浏览系统</span></a></li>
						</ul></li>
					<li class="menu_3"><a href="#">数据管理</a>
						<ul class="nav_mini_ul">
							<li><a href="<?php echo $this->url(array('controller'=>'unit','action'=>'unitadd'),'default', true);?>"><span>添加单位</span></a></li>
							<li><a href="<?php echo $this->url(array('controller'=>'unit','action'=>'unitsearch'),'default', true);?>"><span>浏览单位</span></a></li>
						</ul></li>
					<li class="menu_4"><a href="<?php echo $this->url ( array ('controller' => 'syslog' ), 'default', true )?>">日志管理</a></li>
					
				</ul>
			</div>
			<div class="menu2">
				<div class="out">
					admin：<a href="<?php echo $this->url(array('controller' => 'user', 'action'=> 'updatepassword'),'default', true) ?>">修改密码</a>|<a href="">退出</a>
				</div>
			</div>
		</div>
		<div id="content">
		      <div class="bc_mod">
				<div class="breadcrumbs">
			     <?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" > ");; ?>
		        </div>
		        </div>
			
			<div class="bc_mod">
				<div class="line"></div>
			</div>
		</div>

		<div class="bc_mod">
		
			<?php echo $this->layout()->content ?>				
		</div>

		<div class="bc_mod">
			<div class="line"></div>
		</div>
		<div id="foot_1">61733 &copy; 2000-2012 All rights reserved</div>
  </div>
</body>

</html>
