<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>网站管理系统</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>网站管理</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'user'),
            'default',
            true) ?>">用户管理</a>
		&nbsp;&nbsp;
        <a href="<?php echo $this->url(
            array('controller'=>'acapplication'),
            'default',
            true) ?>">系统管理</a>
       &nbsp;&nbsp;     
       <a href="<?php echo $this->url(
            array('controller'=>'unit'),
            'default',
            true) ?>">部门管理</a>
    </div>
</div>
<?php echo $this->layout()->content ?>
</body>
</html>
