
<?php if ($this->pageCount): ?>
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first,'username'=>$this->username,'sortfield'=>$this->sortfield)); ?>">
    首页
  </a> |
<?php else: ?>
  <span class="disabled">首页</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous,'username'=>$this->username,'sortfield'=>$this->sortfield)); ?>">
    &lt; 上一页
  </a> |
<?php else: ?>
  <span class="disabled">&lt; 上一页</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page,'username'=>$this->username,'sortfield'=>$this->sortfield)); ?>">
    <?= $page; ?>
  </a> |
  <?php else: ?>
    <?= $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next,'username'=>$this->username,'sortfield'=>$this->sortfield)); ?>">
    下一页 &gt;
  </a> |
<?php else: ?>
  <span class="disabled">下一页 &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last,'username'=>$this->username,'sortfield'=>$this->sortfield)); ?>">
    末页
  </a>
<?php else: ?>
  <span class="disabled">末页</span>
<?php endif; ?>
第<?php echo $this->current; ?>页 
共<?php echo $this->pageCount ?>页
<?php endif; ?>

