<p><a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'add'
    ),
    'default',
    true) ?>">添加用户信息</a></p>

<p><a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'search'
    ),
    'default',
    true) ?>">查找用户信息</a></p>
<p><a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'updatepassword'
    ),
    'default',
    true) ?>">修改用户信息</a></p>
    