 请填写用户名进行查找（不输入用户名则查找全部用户）

<?php
$this->form->setAction($this->url());
echo $this->form;

?>
<table>
	<thead>
		<tr>
			<th>用户信息:</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>修改</th>
			<th>删除</th>
			<th>用户名</th>
			<th>邮箱</th>
			<th>手机号</th>
			<th>固定电话</th>
			<th>单位</th>
			<th>创建时间</th>
			<th>用户类型</th>
			<th>状态</th>
		</tr>
		<?php foreach ($this->paginator as $item) :?>
			    <tr>
			    <th><a href="<?php echo $this->url(
			    array(
			    'controller' => 'user',
			    'action'     => 'update',
			    'userid'=>$item->userid
			    ),
			    'default',true) ?>">修改</a></th>
			    
			    <?php if ($item->state!='禁用'): ?>
			    <th class="disabled">删除</th>
				<?php else: ?>
  				<th><a href="<?php echo $this->url(
			    array(
			    'controller' => 'user',
			    'action'     => 'delete',
			    'userid'=>$item->userid
			    ),
			    'default',true) ?>">删除</a></th>
				<?php endif; ?>
			    <th><?php echo $this->escape($item->username) ?></th>
			    <th><?php echo $this->escape($item->email) ?></th>
			    <th><?php echo $this->escape($item->mobile) ?></th>
			    <th><?php echo $this->escape($item->tel) ?></th>
			    <th><?php echo $this->escape($item->unit) ?></th>
			    <th><?php echo $this->escape($item->createdate) ?></th>
			    <th><?php echo $this->escape($item->userstyle) ?></th>
			    <th><?php echo $this->escape($item->state) ?></th>
			    </tr>
     			
		 <?php endforeach ?>
		
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
		'Sliding',
		'user/controls.phtml',
		array('username' => $this->username,
				'sortfield'=>$this->sortfield
			));
?>
