<div class="bc_mod">
			<div class="lan_tit">人员信息浏览</div>
		</div>
<?php
$this->form->setAttrib('class', 'heng');
$this->form->setAction($this->url());
echo $this->form;

?>
<?php if(count($this->entries)>0): ?>
<div class="big-form">
<table>
<thead>
		<tr class="big-form-tit">
			<th width="70px">修改</th>
			<th width="70px">删除</th>
			<th width="70px">用户名</th>
			<th width="90px">邮箱</th>
			<th width="90px">手机号</th>
			<th width="90px">固定电话</th>
			<th width="100px">单位</th>
			<th>创建时间</th>
			<th width="70px">用户类型</th>
			<th width="40px">状态</th>
		</tr>
		</thead>
        <tbody>
		<?php foreach ($this->paginator as $item) :?>
			    <tr height="35" align="center" bgcolor="#FFFFFF">
			    <td><a class="table_edit" href="<?php echo $this->url(
			    array(
			    'controller' => 'user',
			    'action'     => 'update',
			    'userid'=>$item->userid
			    ),
			    'default',true) ?>"><img src="../images/modify.gif"></a></td>
			    
			    <?php if ($item->state!='禁用'): ?>
			    <td class="disabled"></td>
				<?php else: ?>
  				<td><a class="table_del" href="<?php echo $this->url(
			    array(
			    'controller' => 'user',
			    'action'     => 'delete',
			    'userid'=>$item->userid
			    ),
			    'default',true) ?>"><img src="../images/del.gif"></a></td>
				<?php endif; ?>
			    <td><?php echo $this->escape($item->username) ?></td>
			    <td><?php echo $this->escape($item->email) ?></td>
			    <td><?php echo $this->escape($item->mobile) ?></td>
			    <td><?php echo $this->escape($item->tel) ?></td>
			    <td><?php echo $this->escape($item->unit) ?></td>
			    <td><?php echo $this->escape($item->createdate) ?></td>
			    <td><?php echo $this->escape($item->userstyle) ?></td>
			    <td><?php echo $this->escape($item->state) ?></td>
			    </tr>
		 <?php endforeach ?>
	</tbody>
</table>
<?php endif;?>
<?php echo $this->paginationControl($this->paginator,
		'Sliding',
		'user/controls.phtml',
		array('username' => $this->username,
				'sortfield'=>$this->sortfield
			));
?>
</div>
